export const apidata = [
  {
    id: 1,
    name: "Lorem ipsum dolor sit amet consectetur.",
    description: "ይህ ምርት ከፍተኛ ጥራት እና ተመጣጣኝ ዋጋ አለው።",
    category: "tv",
    price: 19.99,
  },
  {
    id: 2,
    name: "ምርት 2",
    description: "በሙሉ የተጠበቀ ላፕቶፕ ምርት።",
    category: "laptop",
    price: 29.99,
  },
  {
    id: 3,
    name: "ምርት 3",
    description: "አስደናቂ የድምፅ ስርጭት ከፍተኛ ጥራት ያለው።",
    category: "speaker",
    price: 49.99,
  },
  {
    id: 4,
    name: "ምርት 4",
    description: "ቀላል ለመጠቀም የተሰራ እና በቤት ውስጥ ለመጠቀም ምርጥ።",
    category: "appliance",
    price: 39.99,
  },
  {
    id: 5,
    name: "ምርት 5",
    description: "ለጎልማሳ የተሰራ የጽሑፍ መቀመጫ።",
    category: "furniture",
    price: 59.99,
  },
  {
    id: 6,
    name: "ምርት 6",
    description: "ከፍተኛ ጥራት ያለው የሞባይል ስልክ።",
    category: "mobile",
    price: 199.99,
  },
  {
    id: 7,
    name: "ምርት 7",
    description: "የቤት ግብስ እና ቀላል ቀይር የሚያስችል ምርት።",
    category: "home",
    price: 24.99,
  },
  {
    id: 8,
    name: "ምርት 8",
    description: "ቀላል እና ተስማሚ ለማንኛውም ተጠቃሚ።",
    category: "tv",
    price: 89.99,
  },
  {
    id: 9,
    name: "ምርት 9",
    description: "የሚሰራ በቀላሉ እና በቤት ውስጥ ለመጠቀም ጥሩ።",
    category: "appliance",
    price: 34.99,
  },
  {
    id: 10,
    name: "ምርት 10",
    description: "ሙዚቃ የሚሰማ እና ጥራት ያለው ስፒከር።",
    category: "speaker",
    price: 69.99,
  },
  {
    id: 11,
    name: "ምርት 11",
    description: "ቀላል እና ምቹ የማያስቸግር ላፕቶፕ።",
    category: "laptop",
    price: 299.99,
  },
  {
    id: 12,
    name: "ምርት 12",
    description: "የተለያዩ ተጠቃሚዎች ለማገልገል ምርጥ።",
    category: "mobile",
    price: 159.99,
  },
  {
    id: 13,
    name: "ምርት 13",
    description: "ቀላል የተጠቀሰ እና ለቤት እጅግ ተስማሚ የሆነ።",
    category: "home",
    price: 44.99,
  },
  {
    id: 14,
    name: "ምርት 14",
    description: "ከፍተኛ ጥራት ያለው የገንዘብ አውታረ ማስተናገድ መሣሪያ።",
    category: "electronics",
    price: 89.99,
  },
  {
    id: 15,
    name: "ምርት 15",
    description: "ለአንደኛ ደረጃ ተጠቃሚ ቀላል የሆነ የሞባይል እቃ።",
    category: "mobile",
    price: 129.99,
  },
  {
    id: 16,
    name: "ምርት 16",
    description: "ስልክ እና አንደኛ ደረጃ ጥራት የሚሰጥ ምርት።",
    category: "electronics",
    price: 179.99,
  },
  {
    id: 17,
    name: "ምርት 17",
    description: "ቀላል የማስተናገድ እና ቤት ውስጥ ተስማሚ የሆነ።",
    category: "furniture",
    price: 79.99,
  },
  {
    id: 18,
    name: "ምርት 18",
    description: "የሙዚቃ ተስማሚ እና ከፍተኛ ጥራት ያለው ስፒከር።",
    category: "speaker",
    price: 99.99,
  },
  {
    id: 19,
    name: "ምርት 19",
    description: "አስደናቂ የሚታወቅ እና ጥራት ያለው ቤት እቃ።",
    category: "home",
    price: 59.99,
  },
  {
    id: 20,
    name: "ምርት 20",
    description: "ከፍተኛ ጥራት ያለው ሙሉ በሙሉ የተሰራ ላፕቶፕ።",
    category: "laptop",
    price: 399.99,
  },
];